name: base

services:
  base:
    image: oceancleanx:base
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ..:/app
    network_mode: service:husarnet
    stdin_open: true
    tty: true

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - ../.husarnet-config:/var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file: ../.env
